### PR TITLE
[BUGS-2788] Use `wp_kses_post` and `esc_attr` instead of `htmlspecialchars`

### PR DESCRIPTION
**Pull request by zzyou**
New PR from https://github.com/pantheon-systems/wp_launch_check/pull/97.

Use `wp_kses_post` to sanitize content for allowed HTML tags for post content.
https://developer.wordpress.org/reference/functions/wp_kses_post/

Use `esc_attr` to escape for HTML attributes.
https://developer.wordpress.org/reference/functions/esc_attr/

### CODE REVIEW

**Comment by zzyou** [comment]
Thank you @danielbachhuber for your help!

**Comment by zzyou** [comment]
@danielbachhuber It seems that the file could not access `esc_attr`?

**Comment by danielbachhuber** [comment]
> It seems that the file could not access `esc_attr`?

Yeah, it looks like WordPress isn't available for the entirety of WP Launch Check, so I guess we can't use `esc_attr()` and `wp_kses_post()`. 

It looks like it's non-trivial to port them over too.

As a replacement for `esc_attr()`, you can use `filter_var( $var, FILTER_SANITIZE_STRING );`

I don't know what a good pure PHP alternative of `wp_kses_post()` might be though. @greg-1-anderson Do you have any suggestions? Here's the behavior we're looking for:

```bash
$ wp shell
wp> wp_kses_post( '<a href="http://apple.com" onclick="javascript:void(0)">Apple</a><script>alert(foo);</script>' );
=> string(47) "<a href="http://apple.com">Apple</a>alert(foo);"
```

**Comment by zzyou** [comment]
For `esc_attr`, could we still use `htmlspecialchars`?

**Comment by danielbachhuber** [comment]
> For `esc_attr`, could we still use `htmlspecialchars`?

I don't think `htmlspecialchars` is quite right in this scenario, because it's encoding them instead of stripping them out.

**Comment by TeslaDethray** [comment]
Closing because a different solution was merged (#97)

**Pull request closed without merging**
