### PR TITLE
Clone to the latest stable release of WP-CLI

### PR DESCRIPTION
**Pull request by danielbachhuber**

### CODE REVIEW

**Comment by danielbachhuber** [comment]
This build actually fails because `git clone --branch` doesn't work on Travis

**Comment by greg-1-anderson** [comment]
I tried to make this build script work for v0.21.1, but could not get it to work.  I got errors such as:
```
phar error: "vendor/symfony/polyfill-mbstring/bootstrap.php" is not a file in phar "/Users/ga/pantheon/wp_launch_check/wp-cli.phar" in phar:///Users/ga/pantheon/wp_launch_check/wp-cli.phar/vendor/composer/autoload_real.php on line 59
```
The script **does** work for HEAD of master.  It seems that the rsync is there to allow locally-edited files to be built into the phar, for ad-hoc testing. Even getting rid of that did not help, though.

Do we really need to build the phar ourselves?  Maybe for the purpose of deploying, we should not use test.sh, but should instead just download the pre-built phar from wordpress.org.  That's what I used for my ad-hoc tests.

**Comment by danielbachhuber** [comment]
> I tried to make this build script work for v0.21.1, but could not get it to work. I got errors such as:

Oh. This is because Symfony is broken right now. I've since fixed it for v0.22.0: https://github.com/wp-cli/wp-cli/pull/2249

You could fork WP-CLI, create a release branch from the tag, and cherry-pick that commit to produce a functional Composer-based install for v0.21.1

> Do we really need to build the phar ourselves?

Yes, because this is how wp_launch_check is currently bundled. The Phar you download from wp-cli.org doesn't include launch check.

**Comment by greg-1-anderson** [comment]
Ah, I see; makes sense.

**Comment by danielbachhuber** [comment]
:ship:

**Pull request closed without merging**
