### PR TITLE
Update TravisCI config, fix checks

### PR DESCRIPTION
**Pull request by kyletaylored**
Build is failing for various reasons, and TravisCI is also pushing all repos to travis-ci.com. Currently fixing up some checks and build errors to help clear other PRs.

### CODE REVIEW

**Comment by kyletaylored** [comment]
As part of this update, I have added a test WPScan API key within the code, but this was required to get a test to pass. I've added an encrypted API key, but these are not available through pull requests from forks. If we wanted to get an official pass, a maintainer would need to create the branch and do the PR within the repo. But all the changes made brings the Travis config up to speed with the travis-ci.com update, moves to the default Linux (xenial) and removes all deprecations.

@danielbachhuber @TeslaDethray any feedback on doing the repo-based branch PR to use the encrypted key?

**Comment by danielbachhuber** [comment]
@kyletaylored For the changes to `.travis.yml`, I'm fine to simply merge it. It's failing on master now anyway.

For your other pull request, can we add you as a collaborator on this repo so that you can create a branch within the repo?

**Comment by kyletaylored** [comment]
Sure, I'd be down with that.

**Comment by kyletaylored** [comment]
@CdrMarks That's just a test key that I added from my own account vs the Pantheon account (that you linked). This is an old PR, so when the other PR gets merged, we would want to use the Pantheon owned enterprise key.

**Pull request merged**
