### PR TITLE
Warn when a multisite's domains differ from Pantheon domains

### LINKED ISSUE #43: When Running a Site Network - check the domains for the env vs domains in WP
We should surface a warning if the lists of domains are out of sync.

### PR DESCRIPTION
**Pull request by danielbachhuber**
Fixes #43

### CODE REVIEW

**Comment by danielbachhuber** [comment]
@stevector #reviewmerge

**Comment by stevector** [comment]
I don't have much experience with multisite so it's a little hard for me to track what's happening in that code. @ataylorme, can you take a look?

**Comment by ataylorme** [comment]
@danielbachhuber The code looks good to me. The only comment I have is listing the WordPress domains that aren't registered with Pantheon in the warning message.

If a multisite install has many subsites/domains tracking down which one (or more) might be a pain.

**Comment by danielbachhuber** [comment]
> The only comment I have is listing the WordPress domains that aren't registered with Pantheon in the warning message.
> 
> If a multisite install has many subsites/domains tracking down which one (or more) might be a pain.

I'm not sure I follow. Can you provide a suggestion on how I should change this?

**Comment by ataylorme** [comment]
@danielbachhuber - Apologies, I didn't scroll right enough to see the `implode( ', ', $diff )` at the end of the message. You can disregard that comment - this looks fine.

**Comment by danielbachhuber** [comment]
@ataylorme Sounds good.

@stevector When it gets closer to releasing v0.7.0, we'll want to do some sanity checking of this feature on the Pantheon environment, given I'm mocking the omnibus call.

**Pull request merged**
