### PR TITLE
[CMS-859] Add theme vulnerability check

### PR DESCRIPTION
**Pull request by kyletaylored**
Even though we use WPScan (formerly WPVulnDB), we only made use of the plugin vulnerabilities and never the theme vulnerabilities. This PR adds in a new command for checking the themes, similar to how `wp launchcheck plugins` works.

There are also a few typos and grammar pieces that were fixed as well.

### CODE REVIEW

**Comment by danielbachhuber** [comment]
Thanks @kyletaylored !

@greg-1-anderson Up for building this into the Phar when you have a moment?

**Comment by ccharlton** [comment]
Build reports:
1. Two instances of "Error: Error establishing a database connection"
1. One instance of of "Error: The 'twentyfifteen' theme could not be found."

**Comment by kyletaylored** [comment]
@danielbachhuber I had committed a lot here, some of it to try and get successful tests to run on TravisCI, so I went ahead and started a TravisCI to Github Actions migration (#107) which should probably get merged first, then we can start adding in these updates. What do you think @greg-1-anderson?

**Review by jazzsequence — APPROVED** [review]
This LGTM. I've tested locally using `wp --require=wp-cli/wp_launch_check/vendor/autoload.php launchcheck themes` and it works as expected. Looks like it's been updated with the main branch, as well, so this should be g2g.

**Pull request merged**
